### ISSUE TITLE
(expo specific) 32 is not a valid sdk version

### ISSUE THREAD

**Issue by osoese** [andy0130tw/web3.js-browser#1]
any chance of directions to upgrade to sdk 35 for expo?

**Comment by andy0130tw** [comment]
Hi!

Thanks for trying it out. However, I cannot figure out how this bundle is related with expo. It should depend on how it is integrated with your app. Can you elaborate on this issue?

**Comment by osoese** [comment]
Hi,

Thank you for the reply. I cannot recall why I posted this to your repo and after looking at it I might have posted my error on the repo I was looking to as a solution (yours) instead of on the repo that was the problem (most likely an expo template repo with web3). I ended up using a different implementation entirely (ethers.js) because every time I get web3 working in expo the expo SDK updates and right now all the examples are deprecated. I was looking for a pure js implementation to include to expo. So, as for how it would work in my project... I would just link to the pure js file as a module.

Thanks again.
